# Test environment for integration testing

name: "monorepo-starter-test"

services:
  postgres-test:
    container_name: postgres-test
    image: postgres:17.4
    env_file:
      - ./apps/api/.env.test
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5433:5432" # Different port to avoid conflicts with dev DB
    volumes:
      - ./test_2_pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate-test:
    image: node:18-alpine
    container_name: migrate-test
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - ./apps/api/.env.test
    environment:
      - DATABASE_URL=postgresql://test:test@postgres-test:5432/test
    command: sh -c "cd /app/packages/database && npx prisma migrate deploy"
    depends_on:
      postgres-test:
        condition: service_healthy
    restart: "no"
    # Use tmpfs for faster test database operations (data won't persist)
    # tmpfs:
    #   - /var/lib/postgresql/data
#   test_pg_data:
#     driver: local
