packages:
  - "apps/*"
  - "packages/*"
catalog:
  typescript: ^5.8.2
  eslint: 9.27.0
  tsup: ^8.4.0
  "@types/node": ^22.15.29
  graphql: ^16.11.0
  zod: ^3.24.2
  "@prisma/client": ^6.8.2
  "prisma": ^6.8.2
  tailwindcss: ^4.1.5
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.1.6
  "@types/react-dom": ^19.1.5
